### ISSUE TITLE
Kata incorrect

### ISSUE THREAD

**Issue by VGib** [Ardemius/TDD-Softeam#1]
Bonjour,

on voit immédiatement que le kata ne marche pas pour le cas suivant:
roll 8 , 2 ,7 ,3 , strike , 6 ,4.

Dans le kata , il faut gérer le cas des strike autrement que par une interface 10, 0 => (un strike = un seul lancé) !

Pouvez-vous fixer ?

**Comment by Ardemius** [comment]
Bonjour,

Je ne comprends pas le problème remonté.

Si je reprends l'exemple donné (avec un dernier lancé à 0, car il manquait le lancé bonus du spare de la dernière frame 6 puis 4), voici le décompte des points : 

8 -> 8
2 -> 10 + 7 = 17
7 -> 24
3 -> 27 + 10 = 37
strike (10) -> 47 + 6 + 4 = 57
6 -> 63
4 -> 67 + 0 = 67
0 -> 67

Je viens de créer localement un TU, et son résultat est bien de 67.
Tout est donc correct, pouvez-vous préciser ce qui vous gêne ?

**Comment by VGib** [comment]
Déjà comme je l'ai dit, normalement un on compte les boules, donc un strike => 10 et pas 10,0 ( car sinon la responsabilité de compter les frames ne revient pas au module qui envoie les résultats , ce qui est un problème d'architecture).

Qu'est ce que donne ce résultat:
18 lancer 4 + 4,
1 lancer 10
2 lancer 5 + 5

Score total 8 * 18 + 10 + 5 + 5 = 164 ? (soit 22 jets et non un tableau de int de 21 , car les règles sont qu' après un strike on a droit à 2 jets, mais à la fin ces jets ne comptent pas comme un strike).

C'est un bon exemple de ce qu'il manque à mon sens dans ce kata : les cas particuliers ....

Le TDD demande de se demander quels sont les cas borderlines et de les implémenter.

Les tests doivent être présents pour signifier que ces uses cases ont bien été considéré et implémenté.

Pour moi le kata est incomplet.

Cordialement

**Comment by Ardemius** [comment]
Reprenons l'exemple donné : 

```
18 lancer 4 + 4,
1 lancer 10
2 lancer 5 + 5
```

Soit 22 frames, plus un lancé bonus du fait du dernier lancé.

Voici le décompte des points : 

```
Frame 1 :
4 -> 4
4 -> 8
Frame 2 : 
4 -> 12
4 -> 16
[...]
Frame 18 : 
4 -> 140
4 -> 144
Frame 19 : 
strike (10) -> 154 + 5 + 5 = 164
Frame 20 : 
5 -> 169
5 -> 174 + 5 = 179
Frame 21 : 
5 -> 184
5 -> 189 + 0
Lancé bonus dû au dernier spare : 
0 -> 189
```

Quand j'ajoute un nouveau TU pour cet exemple, **j'obtiens bien 189**, je ne constate toujours pas de problème 🙂
(Remarque : l'énoncé donne 10 frames comme le maximum pour une partie, j'ai donc pour les besoins de l'exemple augmenté le nombre de frames possibles).

Concernant la remarque "normalement un on compte les boules, donc un strike => 10 et pas 10,0", je ne vois pas de quoi il est question. A quel moment dans le code, le strike est-il traité comme un "10,0" ?

Concernant la remarque sur l'architecture et le "module qui envoie les résultats", le code prend au total une 40e de lignes utiles. Il s'agit d'un cas simple, à des fins d'illustration pour le TDD, et aucun découpage en module n'a été réalisé, car non nécessaire ("KISS" 😉).
Pouvez-vous préciser ce qui vous choque, en donnant plus de détails ?
